package com.grdvp.entity;

public enum Specialite {
    CARDIOLOGIE,
    DERMATOLOGIE,
    GYNECOLOGIE,
    PEDIATRIE,
    OPHTALMOLOGIE,
    ORL,
    ORTHOPEDIE,
    NEUROLOGIE,
    PSYCHIATRIE,
    RADIOLOGIE,
    UROLOGIE,
    GASTROENTEROLOGIE,
    ENDOCRINOLOGIE,
    PNEUMOLOGIE,
    RHEUMATOLOGIE,
    HEMATOLOGIE,
    NEPHROLOGIE,
    ONCOLOGIE
}